//! wxwright-mp: WeChat MP platform API adapter (PRD 3.2 适配器层).
//! Implements wxwright-core's `ImageTransport` with the permanent material
//! upload endpoint, and provides draft box / freepublish calls.
//!
//! Security (PRD 5.6): secrets live in the OS keychain (config file only
//! holds a reference); access_token is never logged (always masked).

use std::io::Read;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};
use wxwright_core::error::{Error, Result};
use wxwright_core::img::ImageTransport;

const API_BASE: &str = "https://api.weixin.qq.com";

// ------------------------------------------------------------------ creds ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Credentials {
    pub appid: String,
    pub secret: String,
}

pub fn config_path() -> std::path::PathBuf {
    wxwright_core::util::config_root().join("config.toml")
}

fn keyring_entry() -> Option<keyring::Entry> {
    keyring::Entry::new("wxwright", "mp-secret").ok()
}

/// Load credentials: env overrides > keychain > config file.
pub fn load_credentials() -> Option<Credentials> {
    if let (Ok(appid), Ok(secret)) = (
        std::env::var("WXWRIGHT_MP_APPID"),
        std::env::var("WXWRIGHT_MP_SECRET"),
    ) {
        if !appid.is_empty() && !secret.is_empty() {
            return Some(Credentials { appid, secret });
        }
    }
    let cfg = std::fs::read_to_string(config_path()).ok()?;
    let value: toml::Value = toml::from_str(&cfg).ok()?;
    let mp = value.get("mp")?;
    let appid = mp.get("appid")?.as_str()?.to_string();
    let secret = match mp.get("secret_ref").and_then(|s| s.as_str()) {
        Some("keyring") => {
            let entry = keyring_entry()?;
            entry.get_password().ok()?
        }
        _ => mp.get("secret")?.as_str()?.to_string(),
    };
    if appid.is_empty() || secret.is_empty() {
        return None;
    }
    Some(Credentials { appid, secret })
}

/// Persist credentials. `use_keyring` stores the secret in the OS keychain
/// and only a reference in the config file (PRD 5.6); otherwise the secret
/// lands in the config file with 0600-ish discretion (documented risk).
pub fn save_credentials(creds: &Credentials, use_keyring: bool) -> Result<()> {
    let path = config_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(Error::Io)?;
    }
    let secret_cell = if use_keyring {
        let entry =
            keyring_entry().ok_or_else(|| Error::Upload("OS keychain unavailable".into()))?;
        entry
            .set_password(&creds.secret)
            .map_err(|e| Error::Upload(format!("keychain write failed: {}", e)))?;
        "secret_ref = \"keyring\"".to_string()
    } else {
        format!("secret = \"{}\"", creds.secret)
    };
    let body = format!(
        "# wxwright configuration (generated by `wxwright login`)\n\n[mp]\nappid = \"{}\"\n{}\n",
        creds.appid, secret_cell
    );
    // Owner-only permissions on Unix: without --no-keyring this file holds the
    // AppSecret in clear text.
    wxwright_core::util::write_private(&path, &body).map_err(Error::Io)?;
    Ok(())
}
pub fn clear_credentials() -> Result<()> {
    if let Some(entry) = keyring_entry() {
        let _ = entry.delete_credential();
    }
    let path = config_path();
    if path.exists() {
        let cfg = std::fs::read_to_string(&path).unwrap_or_default();
        let filtered: String = cfg
            .lines()
            .filter(|l| {
                !l.trim_start().starts_with("appid") && !l.trim_start().starts_with("secret")
            })
            .collect::<Vec<_>>()
            .join("\n");
        wxwright_core::util::write_private(&path, &filtered).map_err(Error::Io)?;
    }
    Ok(())
}

/// Mask a secret for logs (PRD 5.6: access_token always masked).
/// Mask a credential for display. The one implementation lives in
/// `wxwright_core::util`; this used to be a near-identical copy that disagreed
/// on the empty case.
pub fn mask(s: &str) -> String {
    wxwright_core::util::mask_secret(s)
}

// ------------------------------------------------------------------ client ---

#[derive(Debug, Deserialize)]
struct TokenResponse {
    access_token: Option<String>,
    expires_in: Option<u64>,
    errcode: Option<i64>,
    errmsg: Option<String>,
}

#[derive(Debug, Deserialize)]
struct GenericResponse {
    errcode: Option<i64>,
    errmsg: Option<String>,
    #[serde(default)]
    media_id: Option<String>,
    #[serde(default)]
    url: Option<String>,
}

struct TokenCache {
    token: String,
    expires_at: Instant,
}

pub struct MpClient {
    appid: String,
    secret: String,
    agent: ureq::Agent,
    cache: Mutex<Option<TokenCache>>,
}

/// Build the `multipart/form-data` body WeChat's material endpoint expects.
///
/// Pulled out of `upload_material` so it can be asserted on directly: the test
/// it replaces only checked that a hardcoded boundary string was alphanumeric,
/// which says nothing about the body that is actually sent.
fn multipart_body(boundary: &str, filename: &str, mime: &str, bytes: &[u8]) -> Vec<u8> {
    let mut body: Vec<u8> = Vec::new();
    body.extend_from_slice(format!("--{}\r\n", boundary).as_bytes());
    body.extend_from_slice(
        format!(
            "Content-Disposition: form-data; name=\"media\"; filename=\"{}\"\r\nContent-Type: {}\r\n\r\n",
            // A quote in the name would close the header early.
            filename.replace('"', ""),
            mime
        )
        .as_bytes(),
    );
    body.extend_from_slice(bytes);
    body.extend_from_slice(format!("\r\n--{}--\r\n", boundary).as_bytes());
    body
}

impl MpClient {
    pub fn new(creds: Credentials) -> Self {
        MpClient {
            appid: creds.appid,
            secret: creds.secret,
            agent: ureq::AgentBuilder::new()
                .timeout(Duration::from_secs(60))
                .build(),
            cache: Mutex::new(None),
        }
    }

    pub fn appid(&self) -> &str {
        &self.appid
    }

    /// Fresh or cached access_token. Cached value is reused until 5 minutes
    /// before expiry; on token-expiry errors callers may force refresh.
    pub fn access_token(&self, force_refresh: bool) -> Result<String> {
        if !force_refresh {
            if let Ok(guard) = self.cache.lock() {
                if let Some(c) = guard.as_ref() {
                    if Instant::now() < c.expires_at {
                        return Ok(c.token.clone());
                    }
                }
            }
        }
        let url = format!(
            "{}/cgi-bin/token?grant_type=client_credential&appid={}&secret={}",
            API_BASE, self.appid, self.secret
        );
        let resp: TokenResponse = self
            .agent
            .get(&url)
            .call()
            .map_err(ureq_err)?
            .into_json()
            .map_err(|e| Error::Upload(format!("json: {}", e)))?;
        match resp.access_token {
            Some(tok) if !tok.is_empty() => {
                let ttl = resp.expires_in.unwrap_or(7200).saturating_sub(300);
                if let Ok(mut guard) = self.cache.lock() {
                    *guard = Some(TokenCache {
                        token: tok.clone(),
                        expires_at: Instant::now() + Duration::from_secs(ttl),
                    });
                }
                Ok(tok)
            }
            _ => Err(Error::Upload(format!(
                "token fetch failed: errcode={:?} errmsg={:?}",
                resp.errcode,
                resp.errmsg.unwrap_or_default()
            ))),
        }
    }

    /// Upload an image to the permanent material library.
    /// Returns (media_id, mmbiz_url).
    pub fn upload_material(&self, bytes: Vec<u8>, filename: &str) -> Result<(String, String)> {
        self.upload_material_retry(bytes, filename, 2)
    }

    fn upload_material_retry(
        &self,
        bytes: Vec<u8>,
        filename: &str,
        attempts: u32,
    ) -> Result<(String, String)> {
        let mut last_err = String::new();
        for attempt in 0..attempts {
            if attempt > 0 {
                // Exponential backoff, capped: 500ms, 1s, 2s, 4s...
                let backoff = 500u64.saturating_mul(1u64 << attempt.min(3));
                std::thread::sleep(Duration::from_millis(backoff));
            }
            match self.upload_material_once(&bytes, filename) {
                Ok(v) => return Ok(v),
                Err(e) => last_err = e.to_string(),
            }
        }
        Err(Error::Upload(last_err))
    }

    fn upload_material_once(&self, bytes: &[u8], filename: &str) -> Result<(String, String)> {
        let v = self.with_token_retry(|force| self.upload_material_post(bytes, filename, force))?;
        let resp: GenericResponse =
            serde_json::from_value(v).map_err(|e| Error::Upload(format!("decode: {}", e)))?;
        check(&resp)?;
        match (resp.media_id, resp.url) {
            (Some(id), Some(u)) => Ok((id, u)),
            _ => Err(Error::Upload(
                "material upload: missing media_id/url".into(),
            )),
        }
    }

    fn upload_material_post(
        &self,
        bytes: &[u8],
        filename: &str,
        force_refresh: bool,
    ) -> Result<serde_json::Value> {
        let token = self.access_token(force_refresh)?;
        let url = format!(
            "{}/cgi-bin/material/add_material?access_token={}&type=image",
            API_BASE, token
        );
        let boundary = "wxwright boundary 7d3a9c1f";
        let mime = mime_of_filename(filename);
        let body = multipart_body(boundary, filename, mime, bytes);

        self.agent
            .post(&url)
            .set(
                "Content-Type",
                &format!("multipart/form-data; boundary={}", boundary),
            )
            .send_bytes(&body)
            .map_err(ureq_err)?
            .into_json()
            .map_err(|e| Error::Upload(format!("json: {}", e)))
    }

    /// Create a draft in the 草稿箱 (Drafts). `thumb_media_id` is required by
    /// the API; pass the media_id of one of the uploaded article images.
    pub fn draft_add(&self, article: &DraftArticle) -> Result<String> {
        let payload = serde_json::json!({
            "articles": [{
                "title": article.title,
                "author": article.author,
                "digest": article.digest,
                "content": article.content_html,
                "content_source_url": article.content_source_url,
                "thumb_media_id": article.thumb_media_id,
                "need_open_comment": 0,
                "only_fans_can_comment": 0,
            }]
        });
        let resp: GenericResponse = self.post_with_token("/cgi-bin/draft/add", &payload)?;
        check(&resp)?;
        resp.media_id
            .ok_or_else(|| Error::Upload("draft add: missing media_id".into()))
    }

    pub fn draft_list(&self, offset: u64, count: u64) -> Result<serde_json::Value> {
        let payload =
            serde_json::json!({ "offset": offset, "count": count.min(20), "no_content": 1 });
        // Official endpoint is batchget (/cgi-bin/draft/batch does not exist -
        // WeChat answered 40066 "invalid url", so this tool had never worked
        // against the live API).
        self.post_with_token_value("/cgi-bin/draft/batchget", &payload)
    }

    pub fn draft_update(&self, media_id: &str, index: u64, article: &DraftArticle) -> Result<()> {
        let payload = serde_json::json!({
            "media_id": media_id,
            "index": index,
            "articles": {
                "title": article.title,
                "author": article.author,
                "digest": article.digest,
                "content": article.content_html,
                "content_source_url": article.content_source_url,
                "thumb_media_id": article.thumb_media_id,
                "need_open_comment": 0,
                "only_fans_can_comment": 0,
            }
        });
        let resp: GenericResponse = self.post_with_token("/cgi-bin/draft/update", &payload)?;
        check(&resp)?;
        Ok(())
    }

    /// 群发 (mass send) via freepublish. Caller must gate on explicit --yes.
    pub fn freepublish_submit(&self, draft_media_id: &str) -> Result<serde_json::Value> {
        let payload = serde_json::json!({ "media_id": draft_media_id });
        self.post_with_token_value("/cgi-bin/freepublish/submit", &payload)
    }

    /// POST a JSON payload with the cached token. `force_refresh` bypasses the
    /// cache (used by the retry path). Returns the raw body so callers decode
    /// into the shape they need.
    fn post_json(
        &self,
        path: &str,
        payload: &serde_json::Value,
        force_refresh: bool,
    ) -> Result<serde_json::Value> {
        let token = self.access_token(force_refresh)?;
        let url = format!("{}{}?access_token={}", API_BASE, path, token);
        self.agent
            .post(&url)
            .send_json(payload.clone())
            .map_err(ureq_err)?
            .into_json()
            .map_err(|e| Error::Upload(format!("json: {}", e)))
    }

    /// Run a token-authenticated request, transparently refreshing the token
    /// once when WeChat reports it as stale. Every authenticated call goes
    /// through here - previously only `post_with_token_value` retried, so a
    /// long session (batch upload, then draft create) died on token expiry.
    fn with_token_retry<F>(&self, call: F) -> Result<serde_json::Value>
    where
        F: Fn(bool) -> Result<serde_json::Value>,
    {
        let resp = call(false)?;
        if is_token_expired(&resp) {
            return call(true);
        }
        Ok(resp)
    }

    fn post_with_token(&self, path: &str, payload: &serde_json::Value) -> Result<GenericResponse> {
        let v = self.with_token_retry(|force| self.post_json(path, payload, force))?;
        serde_json::from_value(v).map_err(|e| Error::Upload(format!("decode: {}", e)))
    }

    fn post_with_token_value(
        &self,
        path: &str,
        payload: &serde_json::Value,
    ) -> Result<serde_json::Value> {
        self.with_token_retry(|force| self.post_json(path, payload, force))
    }
}

#[derive(Debug, Clone, Default)]
pub struct DraftArticle {
    pub title: String,
    pub author: String,
    pub digest: String,
    pub content_html: String,
    pub content_source_url: String,
    pub thumb_media_id: String,
}

impl ImageTransport for MpClient {
    fn fetch(&self, url: &str) -> Result<Vec<u8>> {
        let resp = self.agent.get(url).call().map_err(ureq_err)?;
        let mut buf = Vec::new();
        resp.into_reader()
            .take(64 * 1024 * 1024)
            .read_to_end(&mut buf)
            .map_err(|e| Error::Upload(e.to_string()))?;
        Ok(buf)
    }

    fn upload_material(&self, bytes: Vec<u8>, filename: &str) -> Result<(String, String)> {
        MpClient::upload_material(self, bytes, filename)
    }
}

fn check(resp: &GenericResponse) -> Result<()> {
    match resp.errcode {
        Some(code) if code != 0 => Err(Error::Upload(format!(
            "MP API error {}: {}",
            code,
            resp.errmsg.clone().unwrap_or_default()
        ))),
        _ => Ok(()),
    }
}

/// WeChat error codes that mean "the access_token is stale": 40001 invalid
/// credential, 40014 illegal token, 42001 token expired. Every call site
/// funnels through `with_token_retry` so a long-running session (a batch of
/// image uploads, then a draft create) cannot die half way through.
fn is_token_expired(v: &serde_json::Value) -> bool {
    matches!(
        v.get("errcode").and_then(|c| c.as_i64()),
        Some(40001) | Some(40014) | Some(42001)
    )
}

fn ureq_err(e: ureq::Error) -> Error {
    // ureq renders status errors as "{full_url}: status code {code}", and the
    // full URL carries the AppSecret / access_token as query parameters.
    // Redact before the message can reach stdout, a --json payload or a toast
    // (PRD 5.6: secrets are never logged).
    Error::Upload(format!(
        "http: {}",
        wxwright_core::util::redact_secrets(&e.to_string())
    ))
}

fn mime_of_filename(name: &str) -> &'static str {
    let lower = name.to_ascii_lowercase();
    if lower.ends_with(".png") {
        "image/png"
    } else if lower.ends_with(".jpg") || lower.ends_with(".jpeg") {
        "image/jpeg"
    } else if lower.ends_with(".gif") {
        "image/gif"
    } else if lower.ends_with(".webp") {
        "image/webp"
    } else if lower.ends_with(".bmp") {
        "image/bmp"
    } else {
        "application/octet-stream"
    }
}

/// Network reachability probe for `wxwright doctor` (no credentials needed).
/// Any HTTP response counts as reachable - the endpoint answers 4xx to
/// parameterless requests, which still proves the network path works.
pub fn probe_reachable() -> bool {
    let agent = ureq::AgentBuilder::new()
        .timeout(Duration::from_secs(8))
        .build();
    match agent.get(&format!("{}/cgi-bin/token", API_BASE)).call() {
        Ok(_) => true,
        Err(ureq::Error::Status(_, _)) => true,
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mask_hides_secret() {
        assert_eq!(mask("short"), "***");
        let m = mask("abcdefghij12345678");
        assert!(m.starts_with("abcd"));
        assert!(m.ends_with("5678"));
        assert!(m.contains("****"));
        assert!(!m.contains("abcdefghij12345678"));
    }

    #[test]
    fn mime_detection() {
        assert_eq!(mime_of_filename("a.PNG"), "image/png");
        assert_eq!(mime_of_filename("b.gif"), "image/gif");
        assert_eq!(mime_of_filename("c.weird"), "application/octet-stream");
    }

    #[test]
    fn multipart_body_shape() {
        // Replaces a test that only checked the boundary string was
        // alphanumeric - it never looked at the body at all.
        let boundary = "wxwright boundary 7d3a9c1f";
        let payload: &[u8] = &[0x89, 0x50, 0x4E, 0x47, 0x00, 0xFF];
        let body = multipart_body(boundary, "shot.png", "image/png", payload);
        let text = String::from_utf8_lossy(&body);

        // Opens with the boundary, closes with the terminator.
        assert!(
            text.starts_with(&format!("--{}\r\n", boundary)),
            "must open with the boundary: {text:?}"
        );
        assert!(
            text.ends_with(&format!("\r\n--{}--\r\n", boundary)),
            "must close with the terminator: {text:?}"
        );
        // The part headers name the field WeChat expects and carry the MIME.
        assert!(text.contains("name=\"media\""), "got: {text:?}");
        assert!(text.contains("filename=\"shot.png\""), "got: {text:?}");
        assert!(text.contains("Content-Type: image/png"), "got: {text:?}");
        assert!(text.contains("\r\n\r\n"), "headers end with a blank line");
        // The payload must survive byte-for-byte, including non-UTF-8 bytes.
        let start = body
            .windows(payload.len())
            .position(|w| w == payload)
            .expect("the payload bytes must appear verbatim in the body");
        assert!(start > 0, "the payload must come after the headers");
        // A quote in the file name must not be able to close the header early.
        let evil = multipart_body(boundary, "a\"b.png", "image/png", payload);
        let evil_text = String::from_utf8_lossy(&evil);
        assert!(
            !evil_text.contains("filename=\"a\"b.png\""),
            "an embedded quote must be stripped: {evil_text:?}"
        );
    }

    #[test]
    fn token_expiry_codes_are_recognised() {
        for code in [40001, 40014, 42001] {
            assert!(
                is_token_expired(&serde_json::json!({ "errcode": code })),
                "errcode {code} must trigger a refresh"
            );
        }
        assert!(!is_token_expired(&serde_json::json!({ "errcode": 0 })));
        assert!(!is_token_expired(&serde_json::json!({ "errcode": 48001 })));
        assert!(!is_token_expired(&serde_json::json!({ "media_id": "x" })));
    }

    #[test]
    fn http_errors_never_leak_the_app_secret() {
        // Reproduce the exact string ureq produces for a status error, then
        // run it through the same redaction the client applies.
        let raw = format!(
            "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wx0000&secret={}: status code 401",
            "THE-ACTUAL-APP-SECRET"
        );
        let redacted = wxwright_core::util::redact_secrets(&raw);
        assert!(
            !redacted.contains("THE-ACTUAL-APP-SECRET"),
            "the AppSecret must never survive redaction: {redacted}"
        );
        assert!(redacted.contains("status code 401"), "keep the diagnosis");
    }

    #[test]
    fn config_path_is_inside_the_user_config_dir() {
        let p = config_path();
        assert!(p.to_string_lossy().contains("wxwright"));
        assert!(p.to_string_lossy().ends_with("config.toml"));
    }
}
