//! wxwright-mp: WeChat MP platform API adapter (PRD 3.2 适配器层).
//! Implements wxwright-core's `ImageTransport` with the permanent material
//! upload endpoint, and provides draft box / freepublish calls.
//!
//! Security (PRD 5.6): secrets live in the OS keychain (config file only
//! holds a reference); access_token is never logged (always masked).

use std::io::Read;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};
use wxwright_core::error::{Error, Result};
use wxwright_core::img::ImageTransport;

const API_BASE: &str = "https://api.weixin.qq.com";

// ------------------------------------------------------------------ creds ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Credentials {
    pub appid: String,
    pub secret: String,
}

pub fn config_path() -> std::path::PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join("wxwright")
        .join("config.toml")
}

fn keyring_entry() -> Option<keyring::Entry> {
    keyring::Entry::new("wxwright", "mp-secret").ok()
}

/// Load credentials: env overrides > keychain > config file.
pub fn load_credentials() -> Option<Credentials> {
    if let (Ok(appid), Ok(secret)) = (
        std::env::var("WXWRIGHT_MP_APPID"),
        std::env::var("WXWRIGHT_MP_SECRET"),
    ) {
        if !appid.is_empty() && !secret.is_empty() {
            return Some(Credentials { appid, secret });
        }
    }
    let cfg = std::fs::read_to_string(config_path()).ok()?;
    let value: toml::Value = toml::from_str(&cfg).ok()?;
    let mp = value.get("mp")?;
    let appid = mp.get("appid")?.as_str()?.to_string();
    let secret = match mp.get("secret_ref").and_then(|s| s.as_str()) {
        Some("keyring") => {
            let entry = keyring_entry()?;
            entry.get_password().ok()?
        }
        _ => mp.get("secret")?.as_str()?.to_string(),
    };
    if appid.is_empty() || secret.is_empty() {
        return None;
    }
    Some(Credentials { appid, secret })
}

/// Persist credentials. `use_keyring` stores the secret in the OS keychain
/// and only a reference in the config file (PRD 5.6); otherwise the secret
/// lands in the config file with 0600-ish discretion (documented risk).
pub fn save_credentials(creds: &Credentials, use_keyring: bool) -> Result<()> {
    let path = config_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(Error::Io)?;
    }
    let secret_cell = if use_keyring {
        let entry =
            keyring_entry().ok_or_else(|| Error::Upload("OS keychain unavailable".into()))?;
        entry
            .set_password(&creds.secret)
            .map_err(|e| Error::Upload(format!("keychain write failed: {}", e)))?;
        "secret_ref = \"keyring\"".to_string()
    } else {
        format!("secret = \"{}\"", creds.secret)
    };
    let body = format!(
        "# wxwright configuration (generated by `wxwright login`)\n\n[mp]\nappid = \"{}\"\n{}\n",
        creds.appid, secret_cell
    );
    std::fs::write(&path, body).map_err(Error::Io)?;
    Ok(())
}

pub fn clear_credentials() -> Result<()> {
    if let Some(entry) = keyring_entry() {
        let _ = entry.delete_credential();
    }
    let path = config_path();
    if path.exists() {
        let cfg = std::fs::read_to_string(&path).unwrap_or_default();
        let filtered: String = cfg
            .lines()
            .filter(|l| {
                !l.trim_start().starts_with("appid") && !l.trim_start().starts_with("secret")
            })
            .collect::<Vec<_>>()
            .join("\n");
        std::fs::write(&path, filtered).map_err(Error::Io)?;
    }
    Ok(())
}

/// Mask a secret for logs (PRD 5.6: access_token always masked).
pub fn mask(s: &str) -> String {
    let n = s.chars().count();
    if n <= 8 {
        "***".to_string()
    } else {
        let head: String = s.chars().take(4).collect();
        let tail: String = s.chars().skip(n - 4).collect();
        format!("{}****{}", head, tail)
    }
}

// ------------------------------------------------------------------ client ---

#[derive(Debug, Deserialize)]
struct TokenResponse {
    access_token: Option<String>,
    expires_in: Option<u64>,
    errcode: Option<i64>,
    errmsg: Option<String>,
}

#[derive(Debug, Deserialize)]
struct GenericResponse {
    errcode: Option<i64>,
    errmsg: Option<String>,
    #[serde(default)]
    media_id: Option<String>,
    #[serde(default)]
    url: Option<String>,
}

struct TokenCache {
    token: String,
    expires_at: Instant,
}

pub struct MpClient {
    appid: String,
    secret: String,
    agent: ureq::Agent,
    cache: Mutex<Option<TokenCache>>,
}

impl MpClient {
    pub fn new(creds: Credentials) -> Self {
        MpClient {
            appid: creds.appid,
            secret: creds.secret,
            agent: ureq::AgentBuilder::new()
                .timeout(Duration::from_secs(60))
                .build(),
            cache: Mutex::new(None),
        }
    }

    pub fn appid(&self) -> &str {
        &self.appid
    }

    /// Fresh or cached access_token. Cached value is reused until 5 minutes
    /// before expiry; on token-expiry errors callers may force refresh.
    pub fn access_token(&self, force_refresh: bool) -> Result<String> {
        if !force_refresh {
            if let Ok(guard) = self.cache.lock() {
                if let Some(c) = guard.as_ref() {
                    if Instant::now() < c.expires_at {
                        return Ok(c.token.clone());
                    }
                }
            }
        }
        let url = format!(
            "{}/cgi-bin/token?grant_type=client_credential&appid={}&secret={}",
            API_BASE, self.appid, self.secret
        );
        let resp: TokenResponse = self
            .agent
            .get(&url)
            .call()
            .map_err(ureq_err)?
            .into_json()
            .map_err(|e| Error::Upload(format!("json: {}", e)))?;
        match resp.access_token {
            Some(tok) if !tok.is_empty() => {
                let ttl = resp.expires_in.unwrap_or(7200).saturating_sub(300);
                if let Ok(mut guard) = self.cache.lock() {
                    *guard = Some(TokenCache {
                        token: tok.clone(),
                        expires_at: Instant::now() + Duration::from_secs(ttl),
                    });
                }
                Ok(tok)
            }
            _ => Err(Error::Upload(format!(
                "token fetch failed: errcode={:?} errmsg={:?}",
                resp.errcode,
                resp.errmsg.unwrap_or_default()
            ))),
        }
    }

    /// Upload an image to the permanent material library.
    /// Returns (media_id, mmbiz_url).
    pub fn upload_material(&self, bytes: Vec<u8>, filename: &str) -> Result<(String, String)> {
        self.upload_material_retry(bytes, filename, 2)
    }

    fn upload_material_retry(
        &self,
        bytes: Vec<u8>,
        filename: &str,
        attempts: u32,
    ) -> Result<(String, String)> {
        let mut last_err = String::new();
        for attempt in 0..attempts {
            if attempt > 0 {
                std::thread::sleep(Duration::from_millis(500 * attempt as u64));
            }
            match self.upload_material_once(&bytes, filename) {
                Ok(v) => return Ok(v),
                Err(e) => last_err = e.to_string(),
            }
        }
        Err(Error::Upload(last_err))
    }

    fn upload_material_once(&self, bytes: &[u8], filename: &str) -> Result<(String, String)> {
        let token = self.access_token(false)?;
        let url = format!(
            "{}/cgi-bin/material/add_material?access_token={}&type=image",
            API_BASE, token
        );
        let boundary = "wxwright boundary 7d3a9c1f";
        let mime = mime_of_filename(filename);
        let mut body: Vec<u8> = Vec::new();
        body.extend_from_slice(format!("--{}\r\n", boundary).as_bytes());
        body.extend_from_slice(
            format!(
                "Content-Disposition: form-data; name=\"media\"; filename=\"{}\"\r\nContent-Type: {}\r\n\r\n",
                filename.replace('"', ""),
                mime
            )
            .as_bytes(),
        );
        body.extend_from_slice(bytes);
        body.extend_from_slice(format!("\r\n--{}--\r\n", boundary).as_bytes());

        let resp: GenericResponse = self
            .agent
            .post(&url)
            .set(
                "Content-Type",
                &format!("multipart/form-data; boundary={}", boundary),
            )
            .send_bytes(&body)
            .map_err(ureq_err)?
            .into_json()
            .map_err(|e| Error::Upload(format!("json: {}", e)))?;
        check(&resp)?;
        match (resp.media_id, resp.url) {
            (Some(id), Some(u)) => Ok((id, u)),
            _ => Err(Error::Upload(
                "material upload: missing media_id/url".into(),
            )),
        }
    }

    /// Create a draft in the 草稿箱 (Drafts). `thumb_media_id` is required by
    /// the API; pass the media_id of one of the uploaded article images.
    pub fn draft_add(&self, article: &DraftArticle) -> Result<String> {
        let payload = serde_json::json!({
            "articles": [{
                "title": article.title,
                "author": article.author,
                "digest": article.digest,
                "content": article.content_html,
                "content_source_url": article.content_source_url,
                "thumb_media_id": article.thumb_media_id,
                "need_open_comment": 0,
                "only_fans_can_comment": 0,
            }]
        });
        let resp: GenericResponse = self.post_with_token("/cgi-bin/draft/add", &payload)?;
        check(&resp)?;
        resp.media_id
            .ok_or_else(|| Error::Upload("draft add: missing media_id".into()))
    }

    pub fn draft_list(&self, offset: u64, count: u64) -> Result<serde_json::Value> {
        let payload =
            serde_json::json!({ "offset": offset, "count": count.min(20), "no_content": 1 });
        self.post_with_token_value("/cgi-bin/draft/batch", &payload)
    }

    pub fn draft_update(&self, media_id: &str, index: u64, article: &DraftArticle) -> Result<()> {
        let payload = serde_json::json!({
            "media_id": media_id,
            "index": index,
            "articles": {
                "title": article.title,
                "author": article.author,
                "digest": article.digest,
                "content": article.content_html,
                "content_source_url": article.content_source_url,
                "thumb_media_id": article.thumb_media_id,
                "need_open_comment": 0,
                "only_fans_can_comment": 0,
            }
        });
        let resp: GenericResponse = self.post_with_token("/cgi-bin/draft/update", &payload)?;
        check(&resp)?;
        Ok(())
    }

    /// 群发 (mass send) via freepublish. Caller must gate on explicit --yes.
    pub fn freepublish_submit(&self, draft_media_id: &str) -> Result<serde_json::Value> {
        let payload = serde_json::json!({ "media_id": draft_media_id });
        self.post_with_token_value("/cgi-bin/freepublish/submit", &payload)
    }

    fn post_with_token(&self, path: &str, payload: &serde_json::Value) -> Result<GenericResponse> {
        let token = self.access_token(false)?;
        let url = format!("{}{}?access_token={}", API_BASE, path, token);
        let resp: GenericResponse = self
            .agent
            .post(&url)
            .send_json(payload.clone())
            .map_err(ureq_err)?
            .into_json()
            .map_err(|e| Error::Upload(format!("json: {}", e)))?;
        Ok(resp)
    }

    fn post_with_token_value(
        &self,
        path: &str,
        payload: &serde_json::Value,
    ) -> Result<serde_json::Value> {
        let token = self.access_token(false)?;
        let url = format!("{}{}?access_token={}", API_BASE, path, token);
        let resp: serde_json::Value = self
            .agent
            .post(&url)
            .send_json(payload.clone())
            .map_err(ureq_err)?
            .into_json()
            .map_err(|e| Error::Upload(format!("json: {}", e)))?;
        // Retry once with a fresh token on the standard expired-token codes.
        let code = resp.get("errcode").and_then(|v| v.as_i64()).unwrap_or(0);
        if matches!(code, 40001 | 40014 | 42001) {
            let token = self.access_token(true)?;
            let url = format!("{}{}?access_token={}", API_BASE, path, token);
            let resp: serde_json::Value = self
                .agent
                .post(&url)
                .send_json(payload.clone())
                .map_err(ureq_err)?
                .into_json()
                .map_err(|e| Error::Upload(format!("json: {}", e)))?;
            return Ok(resp);
        }
        Ok(resp)
    }
}

#[derive(Debug, Clone, Default)]
pub struct DraftArticle {
    pub title: String,
    pub author: String,
    pub digest: String,
    pub content_html: String,
    pub content_source_url: String,
    pub thumb_media_id: String,
}

impl ImageTransport for MpClient {
    fn fetch(&self, url: &str) -> Result<Vec<u8>> {
        let resp = self.agent.get(url).call().map_err(ureq_err)?;
        let mut buf = Vec::new();
        resp.into_reader()
            .take(64 * 1024 * 1024)
            .read_to_end(&mut buf)
            .map_err(|e| Error::Upload(e.to_string()))?;
        Ok(buf)
    }

    fn upload_material(&self, bytes: Vec<u8>, filename: &str) -> Result<(String, String)> {
        MpClient::upload_material(self, bytes, filename)
    }
}

fn check(resp: &GenericResponse) -> Result<()> {
    match resp.errcode {
        Some(code) if code != 0 => Err(Error::Upload(format!(
            "MP API error {}: {}",
            code,
            resp.errmsg.clone().unwrap_or_default()
        ))),
        _ => Ok(()),
    }
}

fn ureq_err(e: ureq::Error) -> Error {
    Error::Upload(format!("http: {}", e))
}

fn mime_of_filename(name: &str) -> &'static str {
    let lower = name.to_ascii_lowercase();
    if lower.ends_with(".png") {
        "image/png"
    } else if lower.ends_with(".jpg") || lower.ends_with(".jpeg") {
        "image/jpeg"
    } else if lower.ends_with(".gif") {
        "image/gif"
    } else if lower.ends_with(".webp") {
        "image/webp"
    } else if lower.ends_with(".bmp") {
        "image/bmp"
    } else {
        "application/octet-stream"
    }
}

/// Network reachability probe for `wxwright doctor` (no credentials needed).
/// Any HTTP response counts as reachable - the endpoint answers 4xx to
/// parameterless requests, which still proves the network path works.
pub fn probe_reachable() -> bool {
    let agent = ureq::AgentBuilder::new()
        .timeout(Duration::from_secs(8))
        .build();
    match agent.get(&format!("{}/cgi-bin/token", API_BASE)).call() {
        Ok(_) => true,
        Err(ureq::Error::Status(_, _)) => true,
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mask_hides_secret() {
        assert_eq!(mask("short"), "***");
        let m = mask("abcdefghij12345678");
        assert!(m.starts_with("abcd"));
        assert!(m.ends_with("5678"));
        assert!(m.contains("****"));
        assert!(!m.contains("abcdefghij12345678"));
    }

    #[test]
    fn mime_detection() {
        assert_eq!(mime_of_filename("a.PNG"), "image/png");
        assert_eq!(mime_of_filename("b.gif"), "image/gif");
        assert_eq!(mime_of_filename("c.weird"), "application/octet-stream");
    }

    #[test]
    fn multipart_body_shape() {
        // The client builds multipart manually; verify via upload once with a
        // mocked boundary? Kept simple: format sanity of boundary header.
        let boundary = "wxwright boundary 7d3a9c1f";
        assert!(boundary
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == ' '));
    }
}
