//! Rich-text clipboard payload (PRD 5.5): self-contained text/html flavor
//! plus a plain-text fallback. Windows CF_HTML framing is handled by arboard.

use crate::error::{Error, Result};

pub const HTML_MARK: &str = "<!-- generated by wxwright -->";

pub struct CopyPayload {
    pub html: String,
    pub text: String,
}

/// Build the clipboard payload: html flavor carries a provenance comment;
/// the plain-text fallback is the HTML source (useful when pasting into
/// editors that do not read rich text).
pub fn build_payload(html: &str) -> CopyPayload {
    CopyPayload {
        html: format!("{}\n{}", HTML_MARK, html),
        text: format!("{}\n{}", HTML_MARK, html),
    }
}

pub struct CopyOutcome {
    /// True when the rich text/html flavor was actually written.
    pub html_flavor: bool,
}

/// Write the payload to the system clipboard.
///
/// arboard 3.6 implements the `text/html` flavor on all desktop platforms
/// (Windows `CF_HTML`, macOS `public.html`, Linux `text/html` over X11/Wayland),
/// so we attempt the rich flavor everywhere and fall back to plain text only
/// when it genuinely fails (e.g. a headless CI with no display server). Callers
/// read `html_flavor` to report which path actually happened.
pub fn copy_to_clipboard(html: &str) -> Result<CopyOutcome> {
    let payload = build_payload(html);
    let mut cb = arboard::Clipboard::new().map_err(|e| Error::Clipboard(e.to_string()))?;

    let rich = cb
        .set()
        .html(payload.html.clone(), Some(payload.text.clone()));
    if rich.is_ok() {
        return Ok(CopyOutcome { html_flavor: true });
    }

    // Fallback: plain text so the source is still pasteable somewhere.
    cb.set_text(payload.text.clone())
        .map_err(|e| Error::Clipboard(e.to_string()))?;
    Ok(CopyOutcome { html_flavor: false })
}

/// Copy plain text (used for the agent card and CLI snippets).
pub fn copy_text(text: &str) -> Result<()> {
    let mut cb = arboard::Clipboard::new().map_err(|e| Error::Clipboard(e.to_string()))?;
    cb.set_text(text.to_string())
        .map_err(|e| Error::Clipboard(e.to_string()))
}

/// Probe clipboard availability without writing (doctor).
pub fn probe() -> Result<()> {
    arboard::Clipboard::new()
        .map(|_| ())
        .map_err(|e| Error::Clipboard(e.to_string()))
}

#[cfg(test)]
mod tests {
    #[test]
    fn payload_has_mark() {
        let p = super::build_payload("<section></section>");
        assert!(p.html.starts_with(super::HTML_MARK));
    }
}
